### ISSUE TITLE
java se版本1.8.0_381运行出现错误

### ISSUE THREAD

**Issue by gzelvis** [MoshiCoCo/Apple-Monitor#21]
java -jar apple-monitor-v0.0.9.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: top/misec/applemonitor/AppleMonitorMain has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by liurf-x** [comment]
用jdk17

**Comment by whalucard** [comment]
我用的jdk20也可以
